version: '3'

services:  

  redis:
    image: redis:latest
    hostname: redis

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    volumes:
      - .:/app 
    ports:
      - "5000:5000"
    links:
      - rabbit
      - redis
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: sh ./scripts/run_web.sh

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh ./scripts/run_celery.sh
    volumes:
      - .:/app
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
    stdin_open: true # docker run -i
    tty: true        # docker run -t
      